<a href="https://colab.research.google.com/github/dreyan22/pytorch-deep-learning-adrian/blob/main/00_pytorch_fundamentals_adrian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print("hi")

2.5.1+cu121
hi


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors
Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Count dimensions
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
# You can count dimensions by couting number of square brackets (opening or closing)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape
# Output mean it is a 2x1 tensor

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim
# Output is 2 because 2 dimensions (2 opening brackets)

2

In [ ]:
# Index on 0th axis
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape
# [2, 2] mean 2 rows and 2 columns, resulting to 4 total elementes

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
# Output means we have 1 3x3 tensor

torch.Size([1, 3, 3])

In [ ]:
TENSOR1 = torch.tensor([[5, 2, 8],
                        [1, 4, 9]])

TENSOR2 = torch.tensor([[[1, 7],
                         [6, 3]],

                        [[4, 0],
                         [8, 2]]])

TENSOR3 = torch.tensor([3, 6, 1, 7, 9])

TENSOR4 = torch.tensor([[[2, 4, 6],
                         [1, 3, 5],
                         [7, 8, 9]],

                        [[9, 7, 5],
                         [3, 1, 2],
                         [4, 6, 8]]])

TENSOR5 = torch.tensor([42])

TENSOR6 = torch.tensor([[9, 3],
                        [6, 8]])

TENSOR7 = torch.tensor([[[[5, 1],
                          [3, 4]],

                         [[6, 9],
                          [7, 8]]]])


In [ ]:
def tensor_info(tensor, print_ndim, print_shape):
  print(tensor)
  if print_ndim:
    print("Ndim: ", tensor.ndim)
  if print_shape:
    print("Shape: ", tensor.shape)

In [ ]:
tensor = TENSOR7
tensor

tensor([[[[5, 1],
          [3, 4]],

         [[6, 9],
          [7, 8]]]])

In [ ]:
print_ndim = 1
print_shape = 1

tensor_info(tensor, print_ndim, print_shape)

tensor([[[[5, 1],
          [3, 4]],

         [[6, 9],
          [7, 8]]]])
Ndim:  4
Shape:  torch.Size([1, 2, 2, 2])


### `tensor.unsqueeze(dim)`
#### unsqueeze(dim)
#### After adding 1 new dimension with unsqueeze(dim), the tensor’s total dimensions become n + 1.
#### The parameter dim determines where the new size-1 dimension is inserted, effectively shifting existing dimensions to the right.

In [ ]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
tensor.ndim

2

In [ ]:
tensor.unsqueeze(0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
tensor.unsqueeze(1)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [ ]:
tensor.unsqueeze(2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])