## Tensor Basics

### Element-wise Addition and in-place addition, multiplication, division

In [1]:
import torch

In [2]:
x = torch.empty(2, 2, 3)
x = torch.rand(2, 2)
x = torch.zeros(2, 2, dtype=torch.float16)
x = torch.tensor([2.5, 0.1])
tensor_type =  x.dtype
size = x.size()

In [3]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x+y
z = torch.add(x, y)
y.add_(x)

tensor([[0.4061, 0.1615],
        [0.5376, 0.2502]])
tensor([[0.6850, 0.9857],
        [0.4009, 0.8233]])


tensor([[1.0910, 1.1472],
        [0.9385, 1.0735]])

### Slicing Operation

In [4]:
x = torch.randint(0, 10, (5, 3))
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())
# you can use .item() if there is only 1 value

tensor([[5, 3, 9],
        [3, 0, 2],
        [1, 5, 4],
        [6, 0, 5],
        [1, 4, 7]])
tensor([5, 3, 1, 6, 1])
tensor([3, 0, 2])
0


### Reshaping tensor

In [5]:
x = torch.randint(0, 10, (4, 4))
print(x)
y = x.view(16) # reshape into 1d vector
print(y)
z = x.view(-1, 8) # we can put -1, then specify other dimension for auto compute
print(z)
print(z.size())

tensor([[6, 3, 9, 8],
        [8, 8, 4, 6],
        [6, 1, 0, 3],
        [2, 2, 3, 1]])
tensor([6, 3, 9, 8, 8, 8, 4, 6, 6, 1, 0, 3, 2, 2, 3, 1])
tensor([[6, 3, 9, 8, 8, 8, 4, 6],
        [6, 1, 0, 3, 2, 2, 3, 1]])
torch.Size([2, 8])


### Converting from Numpy to Tensor

In [12]:
import numpy as np

In [ ]:
a = torch.ones(5)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [10]:
# If the two are in the same cpu, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [14]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a, b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### GPU

In [18]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [22]:
if torch.cuda.is_available():
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    # z.numpy() causes error cause tensor in GPU cant be converted to numpy
    z.to("cpu")
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


### Requires_grad

In [23]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


### Gradient Calculation with Autograd

In [24]:
import torch

In [ ]:
x = torch.randn(3)
print(x)

tensor([-0.3377, -2.0958,  0.0037], requires_grad=True)


In [38]:
x = torch.randn(3, requires_grad=True)
# Now, if we do operations on this tensor, pytorch will save computational graph
print(x)

y = x+2
print(y)

z = y*y*2
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor([-0.9491,  1.8088, -1.1057], requires_grad=True)
tensor([1.0509, 3.8088, 0.8943], grad_fn=<AddBackward0>)
tensor(10.9408, grad_fn=<MeanBackward0>)
tensor([1.4012, 5.0784, 1.1924])
